import type { NextPage, GetStaticProps } from "next";
import React from "react";
import Head from "next/head";
import { Feed } from "../components";
import { Main } from "../styles/common";

const Home = () => {
  return (
    <>
      <Head>
        <title>야옹히어로</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Feed />
      </Main>
    </>
  );
};

export default Home;
