import type { NextPage, GetStaticProps } from "next";
import React, {
  FormEvent,
  useEffect,
  useState,
  useRef,
  useLayoutEffect,
} from "react";
import Head from "next/head";
import { Feed } from "../components";
import { Main } from "../styles/common";
import { IFeedList, IProfile } from "../types";

interface IProps {
  data: {
    feedList: IFeedList;
  };
}

const Home = ({ data }: IProps) => {
  return (
    <>
      <Head>
        <title>야옹히어로</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Feed />
      </Main>
    </>
  );
};


export default Home;
